__all__ = ['AsmItem']

class AsmItem:
    """ Represents an assembly item """

    #region methods

    def gen_str(self, addr:int) -> str:
        """
        Generates a string representation of the item

        :param addr: Address in assembly source
        :return Generated string
        """
        raise NotImplementedError("gen_str has not been implemented.")

    def gen_bytes(self) -> bytes:
        """
        Generates a byte-string representation of the item
        
        :return Generated byte-string
        """
        raise NotImplementedError("gen_bytes has not been implemented.")

    #endregion